/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package equip;

import com.mysql.jdbc.ResultSet;
import javax.swing.UIManager;
import equip.Connector;
import javax.swing.JOptionPane;

/**
 *
 * @author 3
 */
public class Login extends javax.swing.JFrame {

        boolean login=false;
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        //给输入框添加回车响应
        getRootPane().setDefaultButton(B_login);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        L_user = new javax.swing.JLabel();
        L_pwd = new javax.swing.JLabel();
        tx_user = new javax.swing.JTextField();
        tx_pwd = new javax.swing.JTextField();
        B_login = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        L_user.setText("用户名");

        L_pwd.setText("密码");

        B_login.setText("登入");
        B_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_loginActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("楷体", 0, 36)); // NOI18N
        jLabel2.setText("设备信息管理");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(L_user, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(12, 12, 12))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(L_pwd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tx_pwd, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                    .addComponent(tx_user))
                .addGap(85, 85, 85))
            .addGroup(layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(jLabel2)
                .addContainerGap(72, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(B_login)
                .addGap(159, 159, 159))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel2)
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(tx_user)
                    .addComponent(L_user, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(L_pwd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tx_pwd))
                .addGap(23, 23, 23)
                .addComponent(B_login, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void B_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_loginActionPerformed
        // TODO add your handling code here:
        //使用方法isCorrect()判断
        if(true)
        {
        this.setVisible(false);
        new MainWindow().setVisible(true);
        }
        else
        {
//            showRelogin();
            douDong();
        }
    }//GEN-LAST:event_B_loginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
//              UIManager.setLookAndFeel("com.sun.java.swing.plaf.gtk.GTKLookAndFeel");
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Login().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B_login;
    private javax.swing.JLabel L_pwd;
    private javax.swing.JLabel L_user;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField tx_pwd;
    private javax.swing.JTextField tx_user;
    // End of variables declaration//GEN-END:variables

    private boolean isCorrect() {
        try
        {
        
        String name=tx_user.getText().toString();
        String pwd=tx_pwd.getText().toString();
       Connector c=new Connector();
       String sql="select * from user where user='"+name+"' and pwd='"+pwd+"';";
       ResultSet rs=(ResultSet) c.statement.executeQuery(sql);
       if(rs.next())
       {
           login=true;
       }
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
       return login;
    }

    private void showRelogin() {
         String info="用户名或密码不正确";
        int optionType=JOptionPane.OK_OPTION;
        int messageType=JOptionPane.INFORMATION_MESSAGE;
        JOptionPane.showMessageDialog(null, info, "提示", messageType);
        tx_user.setText(null);
        tx_pwd.setText(null);
       
    }

    private void douDong() {
                       int x = this.getX();  
        int y = this.getY();  
        for (int i = 0; i < 15; i++) {  
            if ((i & 1) == 0) {  
                x += 10;  
//                y += 6;  
            } else {  
                x -= 10;  
//                y -= 6;  
            }  
            this.setLocation(x, y);  
            try {  
                Thread.sleep(15);  
            } catch (Exception e1) {  
                e1.printStackTrace();  
            }  
        }
         tx_user.setText(null);
        tx_pwd.setText(null);
        tx_user.grabFocus();
    }
}
