/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package equip;

import javax.swing.JOptionPane;
import equip.Connector;
import equip.MainWindow;

/**
 *
 * @author 3
 */
public class NewMaintain extends javax.swing.JFrame {
    String productId,time,person,contact,log;
    MainWindow mainWindow;

    /**
     * Creates new form NewMaintain
     */
    public NewMaintain(MainWindow m) {
        mainWindow=m;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tx_productId = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tx_time = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tx_person = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tx_contact = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tx_log = new javax.swing.JTextArea();
        B_done = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("产品型号");

        tx_productId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tx_productIdActionPerformed(evt);
            }
        });

        jLabel2.setText("维修时间");

        tx_time.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tx_timeActionPerformed(evt);
            }
        });

        jLabel3.setText("维修人员");

        tx_person.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tx_personActionPerformed(evt);
            }
        });

        jLabel4.setText("联系方式");

        tx_contact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tx_contactActionPerformed(evt);
            }
        });

        jLabel5.setText("编修日志");

        tx_log.setColumns(20);
        tx_log.setRows(5);
        jScrollPane1.setViewportView(tx_log);

        B_done.setText("完成");
        B_done.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_doneActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tx_contact, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tx_person, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tx_time, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tx_productId, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(268, 268, 268)
                        .addComponent(B_done)))
                .addContainerGap(93, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tx_productId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tx_time, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tx_person, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tx_contact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(B_done)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tx_productIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tx_productIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tx_productIdActionPerformed

    private void tx_timeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tx_timeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tx_timeActionPerformed

    private void tx_personActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tx_personActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tx_personActionPerformed

    private void tx_contactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tx_contactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tx_contactActionPerformed

    private void B_doneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_doneActionPerformed
        getInput();
        if(isConfirmed())
        {
            insertMysql();
            showDialog();
        }
    }//GEN-LAST:event_B_doneActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /*
//         * Set the Nimbus look and feel
//         */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /*
//         * If Nimbus (introduced in Java SE 6) is not available, stay with the
//         * default look and feel. For details see
//         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(NewMaintain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(NewMaintain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(NewMaintain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(NewMaintain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /*
//         * Create and display the form
//         */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//
//            public void run() {
//                new NewMaintain().setVisible(true);
//            }
//        });
//    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B_done;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField tx_contact;
    private javax.swing.JTextArea tx_log;
    private javax.swing.JTextField tx_person;
    private javax.swing.JTextField tx_productId;
    private javax.swing.JTextField tx_time;
    // End of variables declaration//GEN-END:variables

    private void getInput() {
        productId=tx_productId.getText().toString();
        time=tx_time.getText().toString();
        person=tx_person.getText().toString();
        contact=tx_contact.getText().toString();
        log=tx_log.getText().toString();
    }

    private boolean isConfirmed() {
         String info="确认插入维修记录？？";
        int optionType=JOptionPane.OK_CANCEL_OPTION;
        int messageType=JOptionPane.WARNING_MESSAGE;
        int result=JOptionPane.showConfirmDialog(null, info, "确认", optionType);
        return result==JOptionPane.OK_OPTION;
    }

    private void showDialog() {
        String info="数据插入成功";
        int optionType=JOptionPane.OK_OPTION;
        int messageType=JOptionPane.INFORMATION_MESSAGE;
        JOptionPane.showMessageDialog(null, info, "提示", messageType);
    }

    private void insertMysql() {
        try
        {
            Connector c=new Connector();
            String sql="insert into maintain(product,time,person,contact,log) values ('"+productId+"','"+time+"','"+person+"','"+contact+"','"+log+"');";
            c.statement.executeUpdate(sql);   
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
        
    }
}
