/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package equip;

import com.mysql.jdbc.ResultSet;
import javax.swing.RowSorter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import java.sql.*;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import equip.Query;
import java.io.File;
import javax.swing.JOptionPane;
/**
 *
 * @author 3
 */
public class Query_log extends javax.swing.JFrame implements TableModelListener{

    ResultSet rs;
    ResultSetMetaData rsm;
    String[] columnNames={"序列号","设备型号","维修时间","维修人员","联系方式","维修日志"};
    Object[][] data =null;
    DefaultTableModel model;
    Statement statement;
  
    String sql = null;
    
    
    
    /**
     * Creates new form Query_log
     */
    public Query_log() {
       
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        dataTable = new javax.swing.JTable();
        B_query = new javax.swing.JButton();
        B_delete = new javax.swing.JButton();
        B_export = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jScrollPane1.setViewportView(dataTable);

        B_query.setText("查询");
        B_query.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_queryActionPerformed(evt);
            }
        });

        B_delete.setText("删除");
        B_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_deleteActionPerformed(evt);
            }
        });

        B_export.setText("导出");
        B_export.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_exportActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(B_query)
                        .addGap(44, 44, 44)
                        .addComponent(B_delete)
                        .addGap(45, 45, 45)
                        .addComponent(B_export)))
                .addContainerGap(98, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(B_query)
                    .addComponent(B_delete)
                    .addComponent(B_export))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void B_queryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_queryActionPerformed
        getSql(); 
        showData();
    }//GEN-LAST:event_B_queryActionPerformed

    private void B_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_deleteActionPerformed
         if (isConfirmed()) {
            deleteData();
            showDialog();
        }
    }//GEN-LAST:event_B_deleteActionPerformed

    private void B_exportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_exportActionPerformed
        deleteFile();
        exportToExcel();
    }//GEN-LAST:event_B_exportActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /*
//         * Set the Nimbus look and feel
//         */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /*
//         * If Nimbus (introduced in Java SE 6) is not available, stay with the
//         * default look and feel. For details see
//         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Query_log.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Query_log.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Query_log.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Query_log.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /*
//         * Create and display the form
//         */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//
//            public void run() {
//                new Query_log().setVisible(true);
//            }
//        });
//    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B_delete;
    private javax.swing.JButton B_export;
    private javax.swing.JButton B_query;
    private javax.swing.JTable dataTable;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void tableChanged(TableModelEvent e) {
        //-1表示空行
        if (e.getColumn() != -1) {
            Object o = null;
            o = dataTable.getValueAt(e.getFirstRow(), 0);
            if (o != null) {
                //转换到模型行
                int select = e.getFirstRow();
                if (select == -1) {
                    return;
                }
                select = dataTable.getRowSorter().convertRowIndexToModel(select);

                try {
                    rs.absolute(select + 1);
                    //更新数据集中某个位置的内容
                    rs.updateObject(e.getColumn() + 1, dataTable.getValueAt(e.getFirstRow(), e.getColumn()));
                    //更新数据库
                    rs.updateRow();

                } catch (SQLException ex) {
                    ex.printStackTrace();
                }
            }
        }
    }

    private boolean isConfirmed() {
         String info = "确认删除所选数据？？";
        int optionType = JOptionPane.OK_CANCEL_OPTION;
        int messageType = JOptionPane.WARNING_MESSAGE;
        int result = JOptionPane.showConfirmDialog(null, info, "确认", optionType);
        return result == JOptionPane.OK_OPTION;
    }

    private void deleteData() {
         int select = dataTable.getSelectedRow();
        if (select == -1) {
            return;
        }
        //把表格的行号转换成model里的行号
        select = dataTable.getRowSorter().convertRowIndexToModel(select);
        try {
            rs.absolute(select + 1);
            rs.deleteRow();
            model.removeRow(select);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void showDialog() {
        String info = "数据删除成功";
        int optionType = JOptionPane.OK_OPTION;
        int messageType = JOptionPane.INFORMATION_MESSAGE;
        JOptionPane.showMessageDialog(null, info, "提示", messageType);
    }

    private void deleteFile() {
         String path="维修日志.xls";
        File file=new File(path);
        if(file.isFile()&&file.exists())
        {
            file.delete();
        }
    }

    private void exportToExcel() {
          try
        {
//            ExcelExporter exp=new ExcelExporter();
//            exp.exportTable(dataTable, new File("results.xls"));
            String heading="维修日志";
            String inscribe=null;
              JTableToExcel je=new JTableToExcel();
              je.export(new File("维修日志.xls"), heading, inscribe, dataTable);
        }
        catch(Exception ex)
        {
            System.out.println(ex.getMessage());
            ex.printStackTrace();
        }
    }

    public void getSql() {
   
                sql = "select * from maintain;";
           
    }

    public void showData() {
         try {
            Connector c = new Connector();
            rs = (ResultSet) c.sm_updatable.executeQuery(sql);
            rsm = rs.getMetaData();

            int row = 0;
            int column = 0;
            int columnCount = rsm.getColumnCount();
            rs.last();
            int rooCount = rs.getRow();
            rs.beforeFirst();
            data = new Object[rooCount][columnCount];
            while (rs.next()) {
                for (column = 0; column < columnCount; column++) {
                    data[row][column] = rs.getObject(column + 1);
                }
                row++;
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
        model = new DefaultTableModel(data, columnNames) {

            public Class getColumnClass(int c) {
                if (dataVector.isEmpty() == false && getValueAt(0, c) != null) {
                    return getValueAt(0, c).getClass();
                } else {
                    return Object.class;
                }
            }
        };
        model.addTableModelListener(this);
        dataTable.setModel(model);
        //实现表格的排序
        RowSorter<DefaultTableModel> sorter = new TableRowSorter<DefaultTableModel>(model);
        dataTable.setRowSorter(sorter);
    }
}
